/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import database.KoneksiDatabase;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import kontrol.DBHapus;
import kontrol.DBSimpan;
import kontrol.DBUbah;
import kontrol.LoginSession;
import kontrol.Pencarian;
import kontrol.PencarianIntegrasi;
import kontrol.Pilihan;
import kontrol.TDModel;

public class FormBarang extends javax.swing.JFrame {
    private Pencarian PencarianData = new Pencarian();
    private Connection koneksi = new KoneksiDatabase().KoneksiDatabase();
    private Statement state_db = null;
    private ResultSet aksi_db = null;
    String _kode ="";
    String nama=LoginSession.getUsername();
    
    public FormBarang() {
        initComponents();
        txt_user.setText(nama);
        Date tggl=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        txt_tgl.setText(sdf.format(tggl)); 
        tgl_masukT.setDate(tggl);
        setTabelData();
    }
    
    private void AturAwalT(){
        txt_namabarangT.setText("");
        txt_hargabarangT.setText("");
        txt_stokbarangT.setText("");
        combo_kategoriT.setSelectedIndex(0);
    }
    
    private void AturAwalU(){
        txt_kodebarangU.setText(_kode);
        txt_namabarangU.setText(new PencarianIntegrasi().getTunggal("tabel_stok", "kode", _kode, "nama"));
        txt_hargabarangU.setText(new PencarianIntegrasi().getTunggal("tabel_stok", "kode", _kode, "harga"));
        txt_stokbarangU.setText(new PencarianIntegrasi().getTunggal("tabel_stok", "kode", _kode, "stok"));
        combo_kategoriU.setSelectedItem(new PencarianIntegrasi().getTunggal("tabel_stok", "kode", _kode, "kategori"));
        ((JTextField)tgl_masukU.getDateEditor().getUiComponent()).setText(new PencarianIntegrasi().getTunggal("tabel_stok","kode",_kode,"tanggal"));
    }
    
    private void setTabelData(){
        tabel_stok.setModel(new TDModel().Stok(PencarianData));
        tabel_stok.setSelectionMode(0);
        for (int i=0; i<tabel_stok.getColumnCount(); i++){
            tabel_stok.getColumnModel().getColumn(i).setResizable(false);
            tabel_stok.getColumnModel().getColumn(i).setPreferredWidth(150);
        }
        tabel_stok.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabel_stok.getTableHeader().setOpaque(false);
        tabel_stok.getTableHeader().setBackground(new Color(232, 67, 147));
        tabel_stok.getTableHeader().setForeground(new Color(255,255,255));
        tabel_stok.setRowHeight(25);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for(int a=0; a<tabel_stok.getColumnCount(); a++)
        {
            tabel_stok.getColumnModel().getColumn(a).setCellRenderer(centerRenderer);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form_tambah = new javax.swing.JDialog();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combo_kategoriT = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_kodebarangT = new rojeru_san.RSMTextFull();
        txt_namabarangT = new rojeru_san.RSMTextFull();
        txt_hargabarangT = new rojeru_san.RSMTextFull();
        txt_stokbarangT = new rojeru_san.RSMTextFull();
        tgl_masukT = new com.toedter.calendar.JDateChooser();
        jPanel15 = new javax.swing.JPanel();
        btn_simpanT = new rojeru_san.RSButton();
        btn_segarkanT = new rojeru_san.RSButton();
        btn_keluarT = new rojeru_san.RSButton();
        form_ubah = new javax.swing.JDialog();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        combo_kategoriU = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_kodebarangU = new rojeru_san.RSMTextFull();
        txt_namabarangU = new rojeru_san.RSMTextFull();
        txt_hargabarangU = new rojeru_san.RSMTextFull();
        txt_stokbarangU = new rojeru_san.RSMTextFull();
        tgl_masukU = new com.toedter.calendar.JDateChooser();
        jPanel18 = new javax.swing.JPanel();
        btn_simpanU = new rojeru_san.RSButton();
        btn_segarkanU = new rojeru_san.RSButton();
        btn_keluarU = new rojeru_san.RSButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_stok = new javax.swing.JTable();
        cari_kolom = new javax.swing.JComboBox();
        btn_hapus = new utilities.gradienbtn();
        btn_ubah = new utilities.gradienbtn();
        btn_tambah = new utilities.gradienbtn();
        cari_data = new rojeru_san.RSMTextFull();
        gradienpanel1 = new utilities.gradienpanel();
        txt_tgl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_x = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        form_tambah.setBackground(new java.awt.Color(255, 255, 255));
        form_tambah.setMinimumSize(new java.awt.Dimension(490, 470));
        form_tambah.setUndecorated(true);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Kode Barang");

        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("Nama Barang");

        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setText("Tanggal");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Harga");

        combo_kategoriT.setBackground(new java.awt.Color(255, 255, 255));
        combo_kategoriT.setModel(new javax.swing.DefaultComboBoxModel(new Pilihan().getKategori()));
        combo_kategoriT.setBorder(null);
        combo_kategoriT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_kategoriTActionPerformed(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Stok Barang");

        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setText("Kategori");

        txt_kodebarangT.setEditable(false);
        txt_kodebarangT.setBackground(new java.awt.Color(255, 255, 255));
        txt_kodebarangT.setPlaceholder("");

        txt_namabarangT.setBackground(new java.awt.Color(255, 255, 255));
        txt_namabarangT.setPlaceholder("Masukkan Nama Barang");

        txt_hargabarangT.setBackground(new java.awt.Color(255, 255, 255));
        txt_hargabarangT.setPlaceholder("Masukkan Harga Barang");

        txt_stokbarangT.setBackground(new java.awt.Color(255, 255, 255));
        txt_stokbarangT.setPlaceholder("Masukkan Stok Barang");

        tgl_masukT.setBackground(new java.awt.Color(255, 255, 255));
        tgl_masukT.setDateFormatString("yyyy-MM-dd");
        tgl_masukT.setEnabled(false);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kodebarangT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_namabarangT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txt_hargabarangT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_kategoriT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tgl_masukT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(txt_stokbarangT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kodebarangT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_namabarangT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hargabarangT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_stokbarangT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_kategoriT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl_masukT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        btn_simpanT.setBorder(null);
        btn_simpanT.setText("SIMPAN");
        btn_simpanT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanTActionPerformed(evt);
            }
        });

        btn_segarkanT.setBorder(null);
        btn_segarkanT.setText("SEGARKAN");
        btn_segarkanT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_segarkanTActionPerformed(evt);
            }
        });

        btn_keluarT.setBorder(null);
        btn_keluarT.setText("KELUAR");
        btn_keluarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_simpanT, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btn_segarkanT, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btn_keluarT, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpanT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_segarkanT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_keluarT, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout form_tambahLayout = new javax.swing.GroupLayout(form_tambah.getContentPane());
        form_tambah.getContentPane().setLayout(form_tambahLayout);
        form_tambahLayout.setHorizontalGroup(
            form_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        form_tambahLayout.setVerticalGroup(
            form_tambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        form_ubah.setBackground(new java.awt.Color(255, 255, 255));
        form_ubah.setMinimumSize(new java.awt.Dimension(490, 470));
        form_ubah.setUndecorated(true);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Kode Barang");

        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Nama Barang");

        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Tanggal");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Harga");

        combo_kategoriU.setBackground(new java.awt.Color(255, 255, 255));
        combo_kategoriU.setModel(new javax.swing.DefaultComboBoxModel(new Pilihan().getKategori()));
        combo_kategoriU.setBorder(null);

        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Stok Barang");

        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Kategori");

        txt_kodebarangU.setEditable(false);
        txt_kodebarangU.setBackground(new java.awt.Color(255, 255, 255));
        txt_kodebarangU.setPlaceholder("");

        txt_namabarangU.setBackground(new java.awt.Color(255, 255, 255));
        txt_namabarangU.setPlaceholder("Masukkan Nama Barang");

        txt_hargabarangU.setBackground(new java.awt.Color(255, 255, 255));
        txt_hargabarangU.setPlaceholder("Masukkan Harga Barang");

        txt_stokbarangU.setBackground(new java.awt.Color(255, 255, 255));
        txt_stokbarangU.setPlaceholder("Masukkan Stok Barang");

        tgl_masukU.setBackground(new java.awt.Color(255, 255, 255));
        tgl_masukU.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kodebarangU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_namabarangU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txt_hargabarangU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(txt_stokbarangU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_kategoriU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tgl_masukU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kodebarangU, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_namabarangU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hargabarangU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_stokbarangU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_kategoriU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl_masukU, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        btn_simpanU.setBorder(null);
        btn_simpanU.setText("SIMPAN");
        btn_simpanU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanUActionPerformed(evt);
            }
        });

        btn_segarkanU.setBorder(null);
        btn_segarkanU.setText("SEGARKAN");
        btn_segarkanU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_segarkanUActionPerformed(evt);
            }
        });

        btn_keluarU.setBorder(null);
        btn_keluarU.setText("KELUAR");
        btn_keluarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_simpanU, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btn_segarkanU, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_keluarU, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpanU, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_keluarU, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_segarkanU, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout form_ubahLayout = new javax.swing.GroupLayout(form_ubah.getContentPane());
        form_ubah.getContentPane().setLayout(form_ubahLayout);
        form_ubahLayout.setHorizontalGroup(
            form_ubahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        form_ubahLayout.setVerticalGroup(
            form_ubahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1360, 770));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1360, 770));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 770));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Kategori");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 692, 121, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(65, 31));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 693, 205, -1));

        tabel_stok.setBackground(new java.awt.Color(255, 255, 255));
        tabel_stok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Stok Barang", "Kategori"
            }
        ));
        tabel_stok.setGridColor(new java.awt.Color(255, 255, 255));
        tabel_stok.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabel_stok.setName(""); // NOI18N
        tabel_stok.setSelectionBackground(new java.awt.Color(232, 67, 147));
        tabel_stok.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabel_stok.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tabel_stok);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 1250, 275));

        cari_kolom.setBackground(new java.awt.Color(255, 255, 255));
        cari_kolom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Barang", "Nama Barang", "Kategori" }));
        cari_kolom.setFocusable(false);
        cari_kolom.setPreferredSize(new java.awt.Dimension(78, 25));
        jPanel1.add(cari_kolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 40, 170, 41));

        btn_hapus.setBorder(null);
        btn_hapus.setText("Hapus");
        btn_hapus.setkEndColor(new java.awt.Color(232, 67, 147));
        btn_hapus.setkHoverEndColor(new java.awt.Color(108, 92, 231));
        btn_hapus.setkHoverForeGround(new java.awt.Color(223, 230, 233));
        btn_hapus.setkHoverStartColor(new java.awt.Color(232, 67, 147));
        btn_hapus.setkSelectedColor(new java.awt.Color(108, 92, 231));
        btn_hapus.setkStartColor(new java.awt.Color(108, 92, 231));
        btn_hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_hapusMouseClicked(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 110, -1));

        btn_ubah.setBorder(null);
        btn_ubah.setText("Ubah");
        btn_ubah.setkEndColor(new java.awt.Color(232, 67, 147));
        btn_ubah.setkHoverEndColor(new java.awt.Color(108, 92, 231));
        btn_ubah.setkHoverForeGround(new java.awt.Color(223, 230, 233));
        btn_ubah.setkHoverStartColor(new java.awt.Color(232, 67, 147));
        btn_ubah.setkSelectedColor(new java.awt.Color(108, 92, 231));
        btn_ubah.setkStartColor(new java.awt.Color(108, 92, 231));
        btn_ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahMouseClicked(evt);
            }
        });
        jPanel1.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 110, -1));

        btn_tambah.setBorder(null);
        btn_tambah.setText("Tambah");
        btn_tambah.setkEndColor(new java.awt.Color(232, 67, 147));
        btn_tambah.setkHoverEndColor(new java.awt.Color(108, 92, 231));
        btn_tambah.setkHoverForeGround(new java.awt.Color(223, 230, 233));
        btn_tambah.setkHoverStartColor(new java.awt.Color(232, 67, 147));
        btn_tambah.setkSelectedColor(new java.awt.Color(108, 92, 231));
        btn_tambah.setkStartColor(new java.awt.Color(108, 92, 231));
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 110, -1));

        cari_data.setBackground(new java.awt.Color(255, 255, 255));
        cari_data.setPlaceholder("Cari Data");
        cari_data.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cari_dataKeyReleased(evt);
            }
        });
        jPanel1.add(cari_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 289, -1, 500));

        gradienpanel1.setkEndColor(new java.awt.Color(108, 92, 231));
        gradienpanel1.setkStartColor(new java.awt.Color(232, 67, 147));
        gradienpanel1.setPreferredSize(new java.awt.Dimension(1360, 280));

        txt_tgl.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txt_tgl.setForeground(new java.awt.Color(223, 230, 233));
        txt_tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tgl.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 230, 233));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo_11.png"))); // NOI18N

        btn_x.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn_x.setForeground(new java.awt.Color(223, 230, 233));
        btn_x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_x.setText("X");
        btn_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_xMousePressed(evt);
            }
        });

        btn_back.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btn_back.setForeground(new java.awt.Color(223, 230, 233));
        btn_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_back.setText("<");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });

        txt_user.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txt_user.setForeground(new java.awt.Color(223, 230, 233));
        txt_user.setText("username");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(223, 230, 233));
        jLabel5.setText("Nama User                   : ");

        javax.swing.GroupLayout gradienpanel1Layout = new javax.swing.GroupLayout(gradienpanel1);
        gradienpanel1.setLayout(gradienpanel1Layout);
        gradienpanel1Layout.setHorizontalGroup(
            gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradienpanel1Layout.createSequentialGroup()
                .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gradienpanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradienpanel1Layout.createSequentialGroup()
                        .addComponent(btn_x, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(txt_tgl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        gradienpanel1Layout.setVerticalGroup(
            gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradienpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradienpanel1Layout.createSequentialGroup()
                        .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_x, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(gradienpanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradienpanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(gradienpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        FormHome Home = new FormHome();
        Home.setLocationRelativeTo(null);
        Home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
            Date tggl=new Date();
            tgl_masukT.setDate(tggl);
            txt_stokbarangT.setText("0");
            form_tambah.setLocationRelativeTo(null);
            form_tambah.setVisible(true);
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseClicked
        if(tabel_stok.getSelectedRowCount()>0){
            _kode = String.valueOf(tabel_stok.getValueAt(tabel_stok.getSelectedRow(), 0));
            tabel_stok.setSelectionMode(0);
            AturAwalU();
            form_ubah.setLocationRelativeTo(null);
            form_ubah.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Tidak ada data yang anda pilih");
        }
    }//GEN-LAST:event_btn_ubahMouseClicked

    private void btn_hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_hapusMouseClicked
         if(tabel_stok.getSelectedRowCount()>0){
            if(JOptionPane.showConfirmDialog(null, "Anda akan menghapus Kode Barang "+tabel_stok.getValueAt(tabel_stok.getSelectedRow(), 0)+" ?")==0){
                new DBHapus().Stok(String.valueOf(tabel_stok.getValueAt(tabel_stok.getSelectedRow(), 0)));
                setTabelData();
            }
        }else
        JOptionPane.showMessageDialog(null, "Tidak ada data yang anda pilih");
    }//GEN-LAST:event_btn_hapusMouseClicked

    private void btn_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xMousePressed
        int ok = JOptionPane.showConfirmDialog(null,
            "Apakah anda yakin ingin keluar?",
            "WARNING!!!",
            JOptionPane.YES_NO_OPTION);
        if(ok==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btn_xMousePressed

    private void combo_kategoriTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_kategoriTActionPerformed
            int pil=combo_kategoriT.getSelectedIndex();
       try{
            state_db = (Statement) koneksi.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            aksi_db = state_db.executeQuery("select right (kode,2) as no_terakhir from tabel_stok order by no_terakhir asc ");
            if(aksi_db.first()==false){
             switch(pil){
                case 0:
                txt_kodebarangT.setText("A001");
                break;
                case 1:
                txt_kodebarangT.setText("B001");
                break;
                case 2:
                txt_kodebarangT.setText("C001");
                break;
                case 3:
                txt_kodebarangT.setText("D001");
                break;
                case 4:
                txt_kodebarangT.setText("E001");
                break;
                case 5:
                txt_kodebarangT.setText("F001");
                break;
                default:
             }   
            }else{
                aksi_db.last();
                int no=aksi_db.getInt(1)+1;
                String cno=String.valueOf(no);
                int pnjg_cno=cno.length();
                for (int i=0;i<2-pnjg_cno;i++){
                    cno="00"+cno;
                }
                switch(pil){    
           case 0:
               txt_kodebarangT.setText("A"+cno);
               break;
           case 1:
               txt_kodebarangT.setText("B"+cno);
               break;
           case 2:
               txt_kodebarangT.setText("C"+cno);
               break;
           case 3:
               txt_kodebarangT.setText("D"+cno);
               break;
           case 4:
               txt_kodebarangT.setText("E"+cno);
               break;
           case 5:
               txt_kodebarangT.setText("F"+cno);
               break;
           default:
                }
            }
        }catch(Exception e){
        }
    }//GEN-LAST:event_combo_kategoriTActionPerformed

    private void btn_segarkanTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_segarkanTActionPerformed
        AturAwalT();
    }//GEN-LAST:event_btn_segarkanTActionPerformed

    private void btn_keluarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarTActionPerformed
        form_tambah.dispose();
    }//GEN-LAST:event_btn_keluarTActionPerformed

    private void btn_segarkanUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_segarkanUActionPerformed
        AturAwalU();
    }//GEN-LAST:event_btn_segarkanUActionPerformed

    private void btn_keluarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarUActionPerformed
        form_ubah.dispose();
    }//GEN-LAST:event_btn_keluarUActionPerformed

    private void btn_simpanTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanTActionPerformed
        ArrayList<String> kesalahan = new ArrayList<String>();
        kesalahan.add("KESALAHAN !");
        String $kode = txt_kodebarangT.getText().trim();
        String $nama = txt_namabarangT.getText().trim();
        String $harga= txt_hargabarangT.getText().trim();
        String $stok= txt_stokbarangT.getText().trim();
        String $kategori=combo_kategoriT.getSelectedItem().toString();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String $tanggal =String.valueOf(sdf.format(tgl_masukT.getDate()));
        if (txt_namabarangT.getText().trim().isEmpty())
            kesalahan.add("Nama Barang tidak dapat di kosongkan.");
        if (txt_hargabarangT.getText().trim().isEmpty())
            kesalahan.add("Harga Barang tidak dapat di kosongkan.");
        if (txt_stokbarangT.getText().trim().isEmpty())
            kesalahan.add("Stok Barang tidak dapat di kosongkan.");
        if (kesalahan.size()<=1){
            new DBSimpan().Stok(
                $kode,
                $nama,
                $harga,
                $stok,
                $kategori,
                $tanggal
            );
            AturAwalT();
            PencarianData.setPencarianKondisi(false);
            setTabelData();
        }else {
        JOptionPane.showMessageDialog(null, kesalahan.toArray());
        }
    }//GEN-LAST:event_btn_simpanTActionPerformed

    private void btn_simpanUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanUActionPerformed
        ArrayList<String> kesalahan = new ArrayList<String>();
        kesalahan.add("KESALAHAN !");
        String kodeu = txt_kodebarangU.getText().trim();
        String namau = txt_namabarangU.getText().trim();
        String hargau = txt_hargabarangU.getText().trim();
        String stoku = txt_stokbarangU.getText().trim();
        String kategoriu=combo_kategoriU.getSelectedItem().toString();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String tanggalu =String.valueOf(sdf.format(tgl_masukU.getDate()));
        if (txt_namabarangU.getText().trim().isEmpty())
            kesalahan.add("Nama Barang tidak dapat di kosongkan.");
        if (txt_hargabarangU.getText().trim().isEmpty())
            kesalahan.add("Harga Barang tidak dapat di kosongkan.");
        if (txt_stokbarangU.getText().trim().isEmpty())
            kesalahan.add("Stok Barang tidak dapat di kosongkan.");
        if (kesalahan.size()<=1){
        new DBUbah().Stok(
                kodeu,
                namau,
                hargau,
                stoku,
                kategoriu,
                tanggalu);
            form_ubah.dispose();
            setTabelData();
            }else{
            JOptionPane.showMessageDialog(null, kesalahan.toArray());
        }
    }//GEN-LAST:event_btn_simpanUActionPerformed

    private void cari_dataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_dataKeyReleased
        if ("Kode Barang".equalsIgnoreCase(cari_kolom.getSelectedItem().toString())){
            PencarianData.setPencarianKolom("kode");
            PencarianData.setPencarianData(cari_data.getText().trim());
            PencarianData.setPencarianKondisi(true);
            setTabelData();
        }
        if ("Nama Barang".equalsIgnoreCase(cari_kolom.getSelectedItem().toString())){
            PencarianData.setPencarianKolom("nama");
            PencarianData.setPencarianData(cari_data.getText().trim());
            PencarianData.setPencarianKondisi(true);
            setTabelData();
        }
        if ("Kategori".equalsIgnoreCase(cari_kolom.getSelectedItem().toString())){
            PencarianData.setPencarianKolom("kategori");
            PencarianData.setPencarianData(cari_data.getText().trim());
            PencarianData.setPencarianKondisi(true);
            setTabelData();
        }
    }//GEN-LAST:event_cari_dataKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private utilities.gradienbtn btn_hapus;
    private rojeru_san.RSButton btn_keluarT;
    private rojeru_san.RSButton btn_keluarU;
    private rojeru_san.RSButton btn_segarkanT;
    private rojeru_san.RSButton btn_segarkanU;
    private rojeru_san.RSButton btn_simpanT;
    private rojeru_san.RSButton btn_simpanU;
    private utilities.gradienbtn btn_tambah;
    private utilities.gradienbtn btn_ubah;
    private javax.swing.JLabel btn_x;
    private rojeru_san.RSMTextFull cari_data;
    private javax.swing.JComboBox cari_kolom;
    private javax.swing.JComboBox combo_kategoriT;
    private javax.swing.JComboBox combo_kategoriU;
    private javax.swing.JDialog form_tambah;
    private javax.swing.JDialog form_ubah;
    private utilities.gradienpanel gradienpanel1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel_stok;
    private com.toedter.calendar.JDateChooser tgl_masukT;
    private com.toedter.calendar.JDateChooser tgl_masukU;
    private rojeru_san.RSMTextFull txt_hargabarangT;
    private rojeru_san.RSMTextFull txt_hargabarangU;
    private rojeru_san.RSMTextFull txt_kodebarangT;
    private rojeru_san.RSMTextFull txt_kodebarangU;
    private rojeru_san.RSMTextFull txt_namabarangT;
    private rojeru_san.RSMTextFull txt_namabarangU;
    private rojeru_san.RSMTextFull txt_stokbarangT;
    private rojeru_san.RSMTextFull txt_stokbarangU;
    private javax.swing.JLabel txt_tgl;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
