/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import database.KoneksiDatabase;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import kontrol.DBHapus;
import kontrol.DBSimpan;
import kontrol.DBUbah;
import kontrol.LoginSession;
import kontrol.Pencarian;
import kontrol.PencarianIntegrasi;
import kontrol.TDModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS PC
 */
public class FormPemesananBarang extends javax.swing.JFrame {
    private Pencarian PencarianData = new Pencarian();
    private Connection koneksi = new KoneksiDatabase().KoneksiDatabase();
    private Statement state_db = null;
    private ResultSet aksi_db = null;
    private String nama=LoginSession.getUsername();
    private String id_pemesanan="";
    private HashMap HM;
    private String kode_pemesanan="";
    

    /**
     * Creates new form FormBarangMasuk
     */
    public FormPemesananBarang() {
        initComponents();
        tanggal();
        txt_user.setText(nama);
        setTabelDataStok();
        setTabelDataPemesanan();
    }
    public void tanggal(){
        Date tggl=new Date();
        SimpleDateFormat simpel=new SimpleDateFormat("yyyy-MM-dd");
        txt_tgl.setText(simpel.format(tggl));
    }
    private void setTabelDataStok(){
        tabel_barang.setModel(new TDModel().Stok(PencarianData));
        tabel_barang.setSelectionMode(0);
        for (int i=0; i<tabel_barang.getColumnCount(); i++){
            tabel_barang.getColumnModel().getColumn(i).setResizable(false);
        }
        tabel_barang.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabel_barang.getTableHeader().setOpaque(false);
        tabel_barang.getTableHeader().setBackground(new Color(232, 67, 147));
        tabel_barang.getTableHeader().setForeground(new Color(255,255,255));
        tabel_barang.setRowHeight(25);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for(int a=0; a<tabel_barang.getColumnCount(); a++)
        {
            tabel_barang.getColumnModel().getColumn(a).setCellRenderer(centerRenderer);
        }
    }
    private void setTabelDataPemesanan(){
        PencarianData.setPencarianKolom("tanggal");
        PencarianData.setPencarianData(txt_tgl.getText().trim());
        PencarianData.setPencarianKondisi(true);
        tabel_pemesanan.setModel(new TDModel().PemesananJumlah(PencarianData));
        tabel_pemesanan.setSelectionMode(0);
        for (int i=0; i<tabel_pemesanan.getColumnCount(); i++){
            tabel_pemesanan.getColumnModel().getColumn(i).setResizable(false);
        }
        tabel_pemesanan.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabel_pemesanan.getTableHeader().setOpaque(false);
        tabel_pemesanan.getTableHeader().setBackground(new Color(232, 67, 147));
        tabel_pemesanan.getTableHeader().setForeground(new Color(255,255,255));
        tabel_pemesanan.setRowHeight(25);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for(int a=0; a<tabel_pemesanan.getColumnCount(); a++)
        {
            tabel_pemesanan.getColumnModel().getColumn(a).setCellRenderer(centerRenderer);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form_ubah = new javax.swing.JDialog();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_kodepemesananU = new rojeru_san.RSMTextFull();
        txt_kodebarangU = new rojeru_san.RSMTextFull();
        txt_namabarangU = new rojeru_san.RSMTextFull();
        txt_jumlahbeliU = new rojeru_san.RSMTextFull();
        tgl_pesanU = new com.toedter.calendar.JDateChooser();
        txt_kategoriU = new rojeru_san.RSMTextFull();
        jPanel18 = new javax.swing.JPanel();
        btn_simpanU = new rojeru_san.RSButton();
        btn_keluarU = new rojeru_san.RSButton();
        jPanel1 = new javax.swing.JPanel();
        txt_caridata = new rojeru_san.RSMTextFull();
        cari_kolom = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_barang = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_pemesanan = new javax.swing.JTable();
        btn_nambah = new utilities.gradienbtn();
        txt_jumlah = new rojeru_san.RSMTextFull();
        btn_kurang = new utilities.gradienbtn();
        btn_konfirmasi = new utilities.gradienbtn();
        btn_tambah = new utilities.gradienbtn();
        btn_ubah = new utilities.gradienbtn();
        gradienpanel1 = new utilities.gradienpanel();
        btn_back = new javax.swing.JLabel();
        txt_tgl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_x = new javax.swing.JLabel();
        txt_user = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        form_ubah.setBackground(new java.awt.Color(255, 255, 255));
        form_ubah.setMinimumSize(new java.awt.Dimension(490, 470));
        form_ubah.setUndecorated(true);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Kode Pemesanan");

        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Kode Barang");

        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setText("Tanggal");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Nama Barang");

        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setText("Jumlah Beli");

        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Kategori");

        txt_kodepemesananU.setEditable(false);
        txt_kodepemesananU.setBackground(new java.awt.Color(255, 255, 255));
        txt_kodepemesananU.setPlaceholder("");

        txt_kodebarangU.setBackground(new java.awt.Color(255, 255, 255));
        txt_kodebarangU.setPlaceholder("Masukkan Kode Barang");

        txt_namabarangU.setBackground(new java.awt.Color(255, 255, 255));
        txt_namabarangU.setPlaceholder("Masukkan Nama Barang");

        txt_jumlahbeliU.setBackground(new java.awt.Color(255, 255, 255));
        txt_jumlahbeliU.setPlaceholder("Masukkan Jumlah Beli");

        tgl_pesanU.setBackground(new java.awt.Color(255, 255, 255));
        tgl_pesanU.setDateFormatString("yyyy-MM-dd");

        txt_kategoriU.setBackground(new java.awt.Color(255, 255, 255));
        txt_kategoriU.setBorder(null);
        txt_kategoriU.setPlaceholder("Masukkan Kategori Barang");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kodepemesananU, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_kodebarangU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txt_namabarangU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(txt_jumlahbeliU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tgl_pesanU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_kategoriU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kodepemesananU, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kodebarangU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_namabarangU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jumlahbeliU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_kategoriU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tgl_pesanU, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        btn_simpanU.setBorder(null);
        btn_simpanU.setText("SIMPAN");
        btn_simpanU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanUActionPerformed(evt);
            }
        });

        btn_keluarU.setBorder(null);
        btn_keluarU.setText("KELUAR");
        btn_keluarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_simpanU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_keluarU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpanU, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_keluarU, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout form_ubahLayout = new javax.swing.GroupLayout(form_ubah.getContentPane());
        form_ubah.getContentPane().setLayout(form_ubahLayout);
        form_ubahLayout.setHorizontalGroup(
            form_ubahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        form_ubahLayout.setVerticalGroup(
            form_ubahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_caridata.setBackground(new java.awt.Color(255, 255, 255));
        txt_caridata.setPlaceholder("Cari Data");
        txt_caridata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_caridataKeyReleased(evt);
            }
        });
        jPanel1.add(txt_caridata, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 16, -1, -1));

        cari_kolom.setBackground(new java.awt.Color(255, 255, 255));
        cari_kolom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kode Barang", "Nama Barang" }));
        cari_kolom.setFocusable(false);
        cari_kolom.setPreferredSize(new java.awt.Dimension(78, 25));
        jPanel1.add(cari_kolom, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 195, 43));

        tabel_barang.setBackground(new java.awt.Color(255, 255, 255));
        tabel_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga", "Stok Barang", "Kategori", "Tanggal"
            }
        ));
        tabel_barang.setGridColor(new java.awt.Color(255, 255, 255));
        tabel_barang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabel_barang.setName(""); // NOI18N
        tabel_barang.setSelectionBackground(new java.awt.Color(232, 67, 147));
        tabel_barang.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabel_barang.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tabel_barang);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 681, 304));

        tabel_pemesanan.setBackground(new java.awt.Color(255, 255, 255));
        tabel_pemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Pemesanan", "Kode Barang", "Nama Barang", "Jumlah Pemesanan", "Tanggal Pemesanan"
            }
        ));
        tabel_pemesanan.setGridColor(new java.awt.Color(255, 255, 255));
        tabel_pemesanan.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabel_pemesanan.setName(""); // NOI18N
        tabel_pemesanan.setSelectionBackground(new java.awt.Color(232, 67, 147));
        tabel_pemesanan.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabel_pemesanan.setShowVerticalLines(false);
        jScrollPane3.setViewportView(tabel_pemesanan);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 64, 650, 310));

        btn_nambah.setBorder(null);
        btn_nambah.setText("Tambah Pemesanan");
        btn_nambah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_nambah.setkEndColor(new java.awt.Color(232, 67, 147));
        btn_nambah.setkHoverEndColor(new java.awt.Color(108, 92, 231));
        btn_nambah.setkHoverForeGround(new java.awt.Color(223, 230, 233));
        btn_nambah.setkHoverStartColor(new java.awt.Color(232, 67, 147));
        btn_nambah.setkSelectedColor(new java.awt.Color(108, 92, 231));
        btn_nambah.setkStartColor(new java.awt.Color(108, 92, 231));
        btn_nambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 200, -1));

        txt_jumlah.setBackground(new java.awt.Color(255, 255, 255));
        txt_jumlah.setPlaceholder("Masukkan Jumlah Pembelian");
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyTyped(evt);
            }
        });
        jPanel1.add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 205, -1));

        btn_kurang.setBorder(null);
        btn_kurang.setText("Kurang");
        btn_kurang.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_kurang.setkEndColor(new java.awt.Color(232, 67, 147));
        btn_kurang.setkHoverEndColor(new java.awt.Color(108, 92, 231));
        btn_kurang.setkHoverForeGround(new java.awt.Color(223, 230, 233));
        btn_kurang.setkHoverStartColor(new java.awt.Color(232, 67, 147));
        btn_kurang.setkSelectedColor(new java.awt.Color(108, 92, 231));
        btn_kurang.setkStartColor(new java.awt.Color(108, 92, 231));
        btn_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kurangActionPerformed(evt);
            }
        });
        jPanel1.add(btn_kurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(705, 12, 200, -1));

        btn_konfirmasi.setBorder(null);
        btn_konfirmasi.setText("Konfirmasi");
        btn_konfirmasi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_konfirmasi.setkEndColor(new java.awt.Color(232, 67, 147));
        btn_konfirmasi.setkHoverEndColor(new java.awt.Color(108, 92, 231));
        btn_konfirmasi.setkHoverForeGround(new java.awt.Color(223, 230, 233));
        btn_konfirmasi.setkHoverStartColor(new java.awt.Color(232, 67, 147));
        btn_konfirmasi.setkSelectedColor(new java.awt.Color(108, 92, 231));
        btn_konfirmasi.setkStartColor(new java.awt.Color(108, 92, 231));
        btn_konfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_konfirmasiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1164, 12, 190, -1));

        btn_tambah.setText("Tambah Barang");
        btn_tambah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_tambah.setkEndColor(new java.awt.Color(232, 67, 147));
        btn_tambah.setkHoverEndColor(new java.awt.Color(108, 92, 231));
        btn_tambah.setkHoverForeGround(new java.awt.Color(223, 230, 233));
        btn_tambah.setkHoverStartColor(new java.awt.Color(232, 67, 147));
        btn_tambah.setkSelectedColor(new java.awt.Color(108, 92, 231));
        btn_tambah.setkStartColor(new java.awt.Color(108, 92, 231));
        btn_tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tambahMouseClicked(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 210, -1));

        btn_ubah.setText("Ubah");
        btn_ubah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_ubah.setkEndColor(new java.awt.Color(232, 67, 147));
        btn_ubah.setkHoverEndColor(new java.awt.Color(108, 92, 231));
        btn_ubah.setkHoverForeGround(new java.awt.Color(223, 230, 233));
        btn_ubah.setkHoverStartColor(new java.awt.Color(232, 67, 147));
        btn_ubah.setkSelectedColor(new java.awt.Color(108, 92, 231));
        btn_ubah.setkStartColor(new java.awt.Color(108, 92, 231));
        btn_ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ubahMouseClicked(evt);
            }
        });
        jPanel1.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 390, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1360, 530));

        gradienpanel1.setkEndColor(new java.awt.Color(108, 92, 231));
        gradienpanel1.setkStartColor(new java.awt.Color(232, 67, 147));
        gradienpanel1.setPreferredSize(new java.awt.Dimension(1360, 280));

        btn_back.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btn_back.setForeground(new java.awt.Color(223, 230, 233));
        btn_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_back.setText("<");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });

        txt_tgl.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txt_tgl.setForeground(new java.awt.Color(223, 230, 233));
        txt_tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_tgl.setText("tanggal");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(223, 230, 233));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logo_11.png"))); // NOI18N

        btn_x.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        btn_x.setForeground(new java.awt.Color(223, 230, 233));
        btn_x.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_x.setText("X");
        btn_x.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_xMousePressed(evt);
            }
        });

        txt_user.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        txt_user.setForeground(new java.awt.Color(223, 230, 233));
        txt_user.setText("username");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(223, 230, 233));
        jLabel5.setText("Nama User : ");

        javax.swing.GroupLayout gradienpanel1Layout = new javax.swing.GroupLayout(gradienpanel1);
        gradienpanel1.setLayout(gradienpanel1Layout);
        gradienpanel1Layout.setHorizontalGroup(
            gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradienpanel1Layout.createSequentialGroup()
                .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradienpanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradienpanel1Layout.createSequentialGroup()
                        .addComponent(btn_x, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(txt_tgl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        gradienpanel1Layout.setVerticalGroup(
            gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradienpanel1Layout.createSequentialGroup()
                .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(gradienpanel1Layout.createSequentialGroup()
                        .addComponent(btn_x, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gradienpanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(gradienpanel1Layout.createSequentialGroup()
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(gradienpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        getContentPane().add(gradienpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nambahActionPerformed
        if(tabel_barang.getSelectedRowCount()>0){
        try{
            state_db = (Statement) koneksi.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
            aksi_db = state_db.executeQuery("select right (kode_pemesanan,3) as no_terakhir from tabel_pemesanan order by no_terakhir asc ");
            if(aksi_db.first()==false){
                id_pemesanan="ID-001";
            }else{
                aksi_db.last();
                int no=aksi_db.getInt(1)+1;
                String cno=String.valueOf(no);
                int pnjg_cno=cno.length();
                for (int i=0;i<2-pnjg_cno;i++){
                        cno="00"+cno;
                }
                    id_pemesanan="ID-"+cno;
            }
                String $idpemesanan=id_pemesanan;
                String $kodebarang = tabel_barang.getValueAt(tabel_barang.getSelectedRow(), 0).toString();
                String $namabarang = tabel_barang.getValueAt(tabel_barang.getSelectedRow(), 1).toString();
                String $kategori = tabel_barang.getValueAt(tabel_barang.getSelectedRow(), 4).toString();
                int $jumlah =Integer.parseInt(txt_jumlah.getText().toString());
                String $tanggal = txt_tgl.getText().toString();
                new DBSimpan().Pemesanan(
                        $idpemesanan,
                        $kodebarang,
                        $namabarang,
                        $jumlah,
                        $kategori,
                        $tanggal
                );
                PencarianData.setPencarianKondisi(false);
                setTabelDataStok();
                setTabelDataPemesanan();
                txt_jumlah.setText("");
        }catch(Exception e){}
        }else{
            JOptionPane.showMessageDialog(null, "Tidak ada data yang anda pilih");
        }
    }//GEN-LAST:event_btn_nambahActionPerformed

    private void txt_jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)|| c==java.awt.event.KeyEvent.VK_BACK_SPACE)|| c==java.awt.event.KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_txt_jumlahKeyTyped

    private void btn_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kurangActionPerformed
        if(tabel_pemesanan.getSelectedRowCount()>0){
            if(JOptionPane.showConfirmDialog(null, "Anda akan menghapus Kode Pemesanan"+tabel_pemesanan.getValueAt(tabel_pemesanan.getSelectedRow(), 0)+" ?")==0){
            new DBHapus().Pemesanan(String.valueOf(tabel_pemesanan.getValueAt(tabel_pemesanan.getSelectedRow(), 0)));
            setTabelDataPemesanan();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Tidak ada data yang anda pilih");
        }
    }//GEN-LAST:event_btn_kurangActionPerformed

    private void btn_konfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_konfirmasiActionPerformed
        try{
            HM=new HashMap();
            HM.put("tanggal", txt_tgl.getText().toString());
            HM.put("nama_kasir", nama);
            String FL=("./src/nota/Nota_Pemesanan.jrxml");
            JasperDesign jasperDesign = JRXmlLoader.load(FL);
            JasperReport jasperReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, HM, koneksi);
            JasperViewer.viewReport(jasperPrint, false);
            }catch (JRException e) {
                        JOptionPane.showMessageDialog(null, "Error " + e);
                    }
    }//GEN-LAST:event_btn_konfirmasiActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        FormHome Home = new FormHome();
        Home.setLocationRelativeTo(null);
        Home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_xMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xMousePressed
        int ok = JOptionPane.showConfirmDialog(null,
            "Apakah anda yakin ingin keluar?",
            "WARNING!!!",
            JOptionPane.YES_NO_OPTION);
        if(ok==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btn_xMousePressed

    private void txt_caridataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_caridataKeyReleased
        if ("Kode Barang".equalsIgnoreCase(cari_kolom.getSelectedItem().toString())){
            PencarianData.setPencarianKolom("kode");
            PencarianData.setPencarianData(txt_caridata.getText().trim());
            PencarianData.setPencarianKondisi(true);
            setTabelDataStok();
        }
        if ("Nama Barang".equalsIgnoreCase(cari_kolom.getSelectedItem().toString())){
            PencarianData.setPencarianKolom("nama");
            PencarianData.setPencarianData(txt_caridata.getText().trim());
            PencarianData.setPencarianKondisi(true);
            setTabelDataStok();
        }
    }//GEN-LAST:event_txt_caridataKeyReleased

    private void btn_tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tambahMouseClicked
        FormBarang formBarang=new FormBarang();
        formBarang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_tambahMouseClicked

    private void btn_ubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ubahMouseClicked
        if(tabel_pemesanan.getSelectedRowCount()>0){
            kode_pemesanan=String.valueOf(tabel_pemesanan.getValueAt(tabel_pemesanan.getSelectedRow(), 0));
            tabel_pemesanan.setSelectionMode(0);
            txt_kodepemesananU.setText(kode_pemesanan);
            txt_kodebarangU.setText(new PencarianIntegrasi().getTunggal("tabel_pemesanan", "kode_pemesanan", kode_pemesanan, "kode_barang"));
            txt_namabarangU.setText(new PencarianIntegrasi().getTunggal("tabel_pemesanan", "kode_pemesanan", kode_pemesanan, "nama_barang"));
            txt_jumlahbeliU.setText(new PencarianIntegrasi().getTunggal("tabel_pemesanan", "kode_pemesanan", kode_pemesanan, "jumlah_beli"));
            txt_kategoriU.setText(new PencarianIntegrasi().getTunggal("tabel_pemesanan", "kode_pemesanan", kode_pemesanan, "kategori"));
            ((JTextField)tgl_pesanU.getDateEditor().getUiComponent()).setText(new PencarianIntegrasi().getTunggal("tabel_pemesanan","kode_pemesanan",kode_pemesanan,"tanggal"));
            form_ubah.setLocationRelativeTo(null);
            form_ubah.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Tidak ada data yang dipilih");
        }
    }//GEN-LAST:event_btn_ubahMouseClicked

    private void btn_simpanUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanUActionPerformed
        ArrayList<String> kesalahan = new ArrayList<String>();
        kesalahan.add("KESALAHAN !");
        String kodeu = txt_kodebarangU.getText().trim();
        String namau = txt_namabarangU.getText().trim();
        int jumlahbeli =Integer.parseInt(txt_jumlahbeliU.getText().trim());
        String kategoriu= txt_kategoriU.getText().trim();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        String tanggalu =String.valueOf(sdf.format(tgl_pesanU.getDate()));
        if (txt_kodebarangU.getText().toString().isEmpty())
            kesalahan.add("Kode Barang tidak boleh kosong");
        if (txt_namabarangU.getText().toString().isEmpty())
            kesalahan.add("Nama Barang tidak boleh kosong");
        if (txt_jumlahbeliU.getText().toString().isEmpty())
            kesalahan.add("Jumlah Beli Barang tidak boleh kosong");
        if (kesalahan.size() <=1){
            new DBUbah().Pemesanan(
                kode_pemesanan,
                kodeu,
                namau,
                jumlahbeli,
                kategoriu,
                tanggalu);
            form_ubah.dispose();
            setTabelDataPemesanan();
        }else{
            JOptionPane.showMessageDialog(null, kesalahan.toArray());
        }
    }//GEN-LAST:event_btn_simpanUActionPerformed

    private void btn_keluarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarUActionPerformed
        form_ubah.dispose();
    }//GEN-LAST:event_btn_keluarUActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private rojeru_san.RSButton btn_keluarU;
    private utilities.gradienbtn btn_konfirmasi;
    private utilities.gradienbtn btn_kurang;
    private utilities.gradienbtn btn_nambah;
    private rojeru_san.RSButton btn_simpanU;
    private utilities.gradienbtn btn_tambah;
    private utilities.gradienbtn btn_ubah;
    private javax.swing.JLabel btn_x;
    private javax.swing.JComboBox cari_kolom;
    private javax.swing.JDialog form_ubah;
    private utilities.gradienpanel gradienpanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabel_barang;
    private javax.swing.JTable tabel_pemesanan;
    private com.toedter.calendar.JDateChooser tgl_pesanU;
    private rojeru_san.RSMTextFull txt_caridata;
    private rojeru_san.RSMTextFull txt_jumlah;
    private rojeru_san.RSMTextFull txt_jumlahbeliU;
    private rojeru_san.RSMTextFull txt_kategoriU;
    private rojeru_san.RSMTextFull txt_kodebarangU;
    private rojeru_san.RSMTextFull txt_kodepemesananU;
    private rojeru_san.RSMTextFull txt_namabarangU;
    private javax.swing.JLabel txt_tgl;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
